<?php
/** @var $viewModel \Perspective\ThreeProducts\ViewModel\ThreeProductsViewModel */
/** @var $escaper \Magento\Framework\Escaper */

$viewModel = $block->getViewModel();
?>

<h2>Вас може зацікавити</h2>

<?php if ($currentProduct = $viewModel->getCurrentProduct()): ?>
    <p>
        <?= $escaper->escapeHtml($currentProduct->getName()) ?><br />
        <?= $escaper->escapeHtml($currentProduct->getSku()) ?><br />
        <?= $escaper->escapeHtml($currentProduct->getFinalPrice()) ?><br />
        <a href="<?= $escaper->escapeUrl($currentProduct->getProductUrl()) ?>">View Product</a><br />
        <?php
        // Выводим массив категорий
        print_r($escaper->escapeHtml(print_r($currentProduct->getCategoryIds(), true)));
        ?>
    </p>
<?php endif; ?>

<?php if ($currentProductCategoryIds = $viewModel->getCurrentCategoryIds()): ?>
    <p>
    <?php foreach ($currentProductCategoryIds as $categoryId) {
            echo 'Category ID: ' . $categoryId . '<br />';    
    }
    ?> 
    </p>
<?php endif; ?>

<?php
$firstCategory = $viewModel->getCurrentFirstCategoryId();

if ($firstCategory) {
    echo 'Category ID: ' . $firstCategory . '<br />';
}
?>

<?php
$products = $viewModel->getProductsByCategoryId($currentProduct, $firstCategory, 10, 3);

foreach ($products as $product) {
    echo 'Product Name: ' . $product->getName() . '<br />';
    echo 'Product SKU: ' . $product->getSku() . '<br />';
    echo 'Product Price: ' . $product->getFinalPrice() . '<br />';
}
?>