<?php
/** @var \Perspective\ThreeProducts\ViewModel\ThreeProductsViewModel $viewModel */
/** @var \Magento\Framework\Escaper $escaper */

$viewModel = $block->getViewModel();
?>

<h2><?php echo __('Вас може зацікавити'); ?></h2>

<?php if ($currentProduct = $viewModel->getCurrentProduct()): ?>
    <?php if ($firstCategory = $viewModel->getCurrentFirstCategoryId()): ?>
        <?php
        $products = $viewModel->getProductsByCategoryId($currentProduct, $firstCategory, 10, 3);

        foreach ($products as $product): 
            $sku = $product->getSku();
            $name = $product->getName();
            $price = $product->getFinalPrice();
            $imageUrl = $product->getMediaConfig()->getMediaUrl($product->getImage());
        ?>
            <div>
                <span><?php echo $sku; ?><br /></span>
                <span><?php echo $name; ?><br /></span>
                <span><?php echo $price; ?><br /></span>
                <img src="<?php echo $imageUrl; ?>" width="100" alt="<?php echo $name; ?>"><br />
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>




